export {default as Home} from './Home';
export {default as Login} from './Login';
export {default as MakeFriend} from './MakeFriend';
export { default as Notification } from './Notification';
export {default as Group} from './Group';
export {default as Register} from './Register';
export {default as Setting} from './Setting';
export {default as Profile} from './Profile';
export { default as Message } from './Message';
export { default as AdminDashboard } from './AdminDashboard';
